Description:  >-
  **WARNING** This template creates AWS VPC NAT Gateway.
  You will be billed for the AWS resources used if you create a stack from this template.

Parameters:
  Tag:
    Description: We tag all AWS resources for your convinience.
    ConstraintDescription: Forward Slash required
    AllowedPattern: '^\S+\/\S+'
    Type: String
    Default: on-aws/workspaces

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://on-aws-us-east-1-master.s3.amazonaws.com/vpc/template.yaml
      Parameters:
        Tag: !Ref Tag

  DIRECTORY:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://raw.githubusercontent.com/mikeplavsky/aws-ad/main/ad.yaml
      Parameters:
        Tag: !Ref Tag
        VPC: !GetAtt VPC.Outputs.VPC
        PrivateSubnets: !GetAtt VPC.Outputs.PrivateSubnets
